name: Pusher
run-name: Push to Epitech

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  is_not_mirror:
    runs-on: ubuntu-latest
    if: github.repository != 'GITHUB ADRESS'
    steps:
      - run: echo OK

  push_to_mirror:
    needs: [is_not_mirror]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}